# Generated by Django 5.2.5 on 2026-09-06 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_order_user_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cashless', 'Безналичный расчёт'), ('on_site', 'Оплата на месте')], default='on_site', max_length=20),
        ),
    ]
