# Generated by Django 5.2.5 on 2026-05-31 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='tasks', through='api.TaskCategory', to='api.category'),
        ),
    ]
